apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::199344360902:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1PMHD6ARFMW2L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::199344360902:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-03T23:43:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1887"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 49aeee5b-fb01-48da-bfc3-95a05220cd09
